### ISSUE TITLE
facing errors with docker-compose up

### ISSUE THREAD

**Issue by helloworldkr** [Hironsan/bertsearch#9]
error:

WARNING: The PATH_MODEL variable is not set. Defaulting to a blank string.
Starting bertsearch-master_elasticsearch_1 ... 
Creating bertsearch-master_bertserving_1   ... error

ERROR: for bertsearch-master_bertserving_1  Cannot create container for service Starting bertsearch-master_elasticsearch_1 ... done
phanumeric characters

ERROR: for bertserving  Cannot create container for service bertserving: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: Encountered errors while bringing up the project.

**Comment by Hironsan** [comment]
Please specify `PATH_MODEL` as an environment variable.

**Comment by helloworldkr** [comment]
@Hironsan  I have added as the path model as instructed, still getting the error

![Selection_002](https://user-images.githubusercontent.com/9402190/69488971-b9e71080-0e97-11ea-9cc8-ab63f907617d.png)

**Comment by Hironsan** [comment]
You should not use sudo.

```bash
❯ export PATH_MODEL=./cased_L-12_H-768_A-12
❯ printenv | grep PATH_MODEL
PATH_MODEL=./cased_L-12_H-768_A-12
❯ sudo printenv | grep PATH_MODEL
```

**Comment by helloworldkr** [comment]
thanks @Hironsan

**Comment by codeAshu** [comment]
The problem is that you are running `sudo docker-compose` and the PATH_MODEL env variable doesn't exists for sudoers. you need to add environment variables to sudoers file via 
run command `sudo visudo`
add a line `Defaults env_keep += PATH_MODEL `
Now if you issue 
`sudo printenv | grep PATH_MODEL`
It will show the env command.
